import type { Metadata } from "next";
import "./globals.css";
import Header from './Header';
import Providers from "./Providers";
import Footer from './Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700">
        <Providers>
          <Header />
          <div className="max-w-6xl mx-auto">
            {children}
          </div>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
